on: push

name: Deploy to Amazon S3

jobs:
  build:
    environment: Teamclerks.net
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build
        env:
          NODE_ENV: production
          CI: true
        run: npm run build

      - name: Verify build output
        run: |
          echo "Checking build output..."
          ls -la build/
          echo "Checking that folder structure was generated..."
          expected_folders=("hello-world" "testing-all-the-markdown" "about" "archive")
          for folder in "${expected_folders[@]}"; do
            if [ -d "build/$folder" ]; then
              echo "✅ $folder/ directory exists"
              if [ -f "build/$folder/index.html" ]; then
                echo "✅ $folder/index.html exists"
              else
                echo "❌ $folder/index.html missing!"
                exit 1
              fi
            else
              echo "❌ $folder/ directory missing!"
              exit 1
            fi
          done
          echo "Checking that 404.html exists..."
          if [ -f "build/404.html" ]; then
            echo "✅ 404.html exists"
          else
            echo "❌ 404.html missing!"
            exit 1
          fi
          echo "Checking metadata in hello-world/index.html..."
          if grep -q 'content="https://blog.teamclerks.net/hello-world"' build/hello-world/index.html; then
            echo "✅ Production URLs are correct!"
          else
            echo "URL not found - checking for placeholder..."
            if grep -q 'content="http://sveltekit-prerender/hello-world"' build/hello-world/index.html; then
              echo "❌ WARNING: Placeholder URL found!"
              exit 1
            else
              echo "❌ No URL found in metadata"
              exit 1
            fi
          fi

      - name: Deploy
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-west-1
      - run: |
          aws s3 sync build s3://teamclerks.net
      - run: |
          aws cloudfront create-invalidation --distribution-id EHWI3ENCZ21KS --paths "/*"
