on: push

name: Deploy to Amazon S3

jobs:
  build:
    environment: Teamclerks.net
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build
        env:
          NODE_ENV: production
          CI: true
        run: npm run build

      - name: Deploy
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-west-1
      - run: |
          aws s3 sync build s3://teamclerks.net
      - run: |
          aws cloudfront create-invalidation --distribution-id EHWI3ENCZ21KS --paths "/*"
