on:
  release:
    types: [created]

name: Deploy to Amazon S3
environment: Teamclerks.net

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present

      - name: Deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-west-1
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
#          AWS_REGION: us-west-1
#          region: us-west-1
#          bucket: teamclerks.net
#          skip_cleanup: true
#          acl: public_read
#          local_dir: public
      - run: npm run deploy
